spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_prod
    username: ${PROD_USERNAME}
    password: ${PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
  sql:
    init:
      platform: mysql