spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_dev
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  sql:
    init:
      platform: mysql
#    properties:
#      hibernate:
#        hbm2ddl:
#          delimiter: ";"
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: mySQL_database_setup.sql